### ISSUE TITLE
Explore different tools/algorithms to auto-generate tags

### ISSUE THREAD

**Issue by sacmax** [DataKind-BLR/PrathamBooks-Sprint-2018#7]
Explore methodologies/tools/algorithms to generate tags based on the context of the story. Please come up with a small write-up covering the process and necessary links and do push it to the repository. Please add relevant examples wherever possible.  If you create a script/notebook, do push it to the repository.

**Comment by arnabbiswas1** [comment]
@deepakshankar94 Here you go.

**Comment by githubssn** [comment]
i would like to contribute to this as well..

**Comment by githubssn** [comment]
Hello Arnab,


I went through the data to do some data exploration and had a few suggestions:-

  *   I think that we do need some more data to go about the analysis. Data of about 300 stories and their content would be required to start data analysis as a prototype. Currently we have content of only a few stories in the story pages data. Could we get data of story category, pages and tags for about 300 stories? Could you share the complete data of the story category, content <pages> and tags for the stories? <Currently we have data of only 4 stories in the story-pages csv file while story-tags has data of 50 stories. Essentially we dont have all the attributes of the 50 stories.>
  *   Upon browsing the website, I find that there is a lot of languages. Perhaps we could do the initial analysis on 300 English stories before we go to other languages. Please ignore if this is already as per initial plan.
  *   I felt that the data could be normalized better. Eg. some features like language, organization_name, story title, story english title, story status, story summary,  etc could be associated with story-category/tags rather than story page so they do not repeat. Not sure if it is possible to change that at this stage.
  *   In terms of overall approach, we can do Topic Modeling for generating tags.


Do we plan to connect this weekend? Let me know.


regards,

Sneha


________________________________

**Comment by arnabbiswas1** [comment]
- [ ] ABCD
- [ ] ABCD

**Comment by arnabbiswas1** [comment]
Reopening the issue as it was closed by mistake.

**Comment by arnabbiswas1** [comment]
The following wiki has been created to track the initial set of methodologies to be evaluated: https://github.com/DataKind-BLR/PrathamBooks-Sprint-2018/wiki/Methodologies-to-Evaluate

Separate issues will be raised as we explore individual issues. Hence closing.
